apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-counter
  description: デモンストレーション用のサービスです
  labels:
    app: counter
  annotations:
    github.com/project-slug: quarkusdroneshop/counter
spec:
  type: website
  owner: user:default/nmushino
  lifecycle: production