apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-counter
  description: カウンター業務のマイクロサービスです
  labels:
    app: counter
  annotations:
    github.com/project-slug: quarkusdroneshop/counter
    backstage.io/kubernetes-label-selector: 'app=counter'
    backstage.io/kubernetes-namespace: quarkusdroneshop-demo
    backstage.io/kubernetes-cluster: a-cluster
spec:
  type: service
  owner: user:default/nmushino
  lifecycle: production
  system: a-cluster
  providesApis:
    - quarkusdroneshop-counter-api
  kubernetes:
    serviceLocatorMethod: 'multiTenant'
    auth:
      defaultAuthType: serviceAccount
    clusters:
      - name: a-cluster
        skipTLSVerify: true
        authProvider: serviceAccount