apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-counter
  description: カウンター業務のマイクロサービスです
  labels:
    app: counter
  annotations:
    github.com/project-slug: quarkusdroneshop/counter
    backstage.io/kubernetes-label-selector: 'app=counter'
    backstage.io/kubernetes-namespace: quarkusdroneshop-counter
    backstage.io/kubernetes-cluster: a-cluster
spec:
  type: service
  owner: user:default/nmushino
  lifecycle: production
  system: Asite
  providesApis:
    - quarkusdroneshop-counter-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: quarkusdroneshop-counter-api
  description: カウンター業務API
spec:
  type: openapi
  lifecycle: production
  owner: user:default/nmushino
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: quarkusdroneshop-counter API
        version: 1.0.0
      paths:
        /counter:
          get:
            summary: カウンター情報を取得
            responses:
              '200':
                description: OK