apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-counter
  description: カウンター業務のマイクロサービスです
  labels:
    app: counter
  annotations:
    github.com/project-slug: quarkusdroneshop/quarkusdroneshop-counter
    backstage.io/kubernetes-id: quarkusdroneshop-counter
    backstage.io/kubernetes-cluster: sandbox1332
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=quarkusdroneshop-counter
    tektonci.io/pipeline: build-and-push-quarkusdroneshop-counter
    tektonci.io/pipelineNamespace: quarkusdroneshop-cicd
    tekton.dev/cicd: "true"
    janus-idp.io/tekton: "true"
spec:
  type: microservice
  owner: user:default/nmushino
  lifecycle: production
  system: sandbox1332
  dependsOn:
    - component:quarkusdroneshop-qdca10
    - component:quarkusdroneshop-qdca10pro
    - component:quarkusdroneshop-inventory
    - resource:droneshopdb-postgresql
    - resource:shop-cluster-kafka
    - resource:shop-asite-orders-in
    - resource:shop-bsite-orders-up
  consumesApis:
    - kafka-shop-asite-orders-in
    - kafka-shop-bsite-orders-up
  providesApis:
    - kafka-qdca10-in
    - kafka-qdca10pro-in
    - kafka-web-updates
